# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  type: website
  title: sif-quarto
execute: 
  freeze: auto # so R/Python code only runs locally

profile:
  default: en
  group: [en, lt]
