# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  type: website
  output-dir: docs
  preview: 
    browser: true
execute: 
  freeze: auto # so R/Python code only runs locally

profile:
  default: english
  group: [english, lithuanian]
