# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  output-dir: docs/en

lang: en

website:
  title: "Lydekai Paliepus"
  description: "Sveikos ekosistemos kintančiame pasaulyje"
  favicon: images/SIF-LOGO-Lt-1000px.webp
  site-url: https://sif-quarto.drtreimer.com
  repo-url: https://github.com/stormeyseas/sif-quarto.github.io
  reader-mode: false

# Navbar options (see https://quarto.org/docs/reference/projects/websites.html#navbar)
  navbar: 
    title: false
    logo: images/SIF-LOGO-Lt-1000px.webp
    pinned: true
    collapse: true
    # List of items for the each section of the navbar (left, right, center)
    center: 
      - text: "Pradžia"
        href: index.qmd
      - text: "Puslapiai"
        href: pages/empty.qmd
        menu:
        - text: "Programele"
          href: pages/empty.qmd
        - text: "Zvejams"
          href: pages/empty.qmd
        - text: "Valdymui"
          href: pages/empty.qmd
        - text: "Mokslui"
          href: pages/empty.qmd
        - text: "Modeliai"
          href: pages/empty.qmd
        - text: "Duomenys"
          href: pages/empty.qmd
      - text: "Grupė"
        href: pages/empty.qmd
      - text: "Media"
        href: pages/empty.qmd
      - text: "Susisiekite"
        href: pages/empty.qmd
    right:
      # - text: ![](/images/gb.svg){fig-alt="View in English"}
      #   href: <link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('/en/','/lt/');" class="btn"><i class="fa fa-language"></i> Switch to Lithuanian </button>
      - text: <link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('/en/','/lt/');" class="btn"><i class="fa fa-language"></i> Switch to Lithuanian </button>
    toggle-position: right # The position of the collapsed navbar toggle in responsive mode
  page-navigation: false # Provide next and previous article links in footer
  back-to-top-navigation: true

format:
  html:
    theme:
      light: [lightly, theme-light.scss]
      dark: darkly
    # css: sif-styles.css
    page-layout: full
    grid:
      sidebar-width: 350px
      body-width: 1250px
      margin-width: 150px
      gutter-width: 2em
    toc: false
    fig-responsive: true
    include-after-body: 
      file: theming/footer.html
