# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  title: "Sustainable Inland Fisheries | Healthy ecosystems in a changing world"
  output-dir: docs/en/

lang: en-GB

website:
  title: "Sustainable Inland Fisheries"
  description: "Healthy ecosystems in a changing world"
  favicon: images/SIF-logo-540x330.gif
  # site-url: https://sif-quarto.drtreimer.com
  # repo-url: https://github.com/stormeyseas/sif-quarto.github.io
  page-navigation: false
  back-to-top-navigation: true
  navbar: 
    background: light
    foreground: dark
    title: false
    logo: images/SIF-logo-540x330.gif
    pinned: false
    collapse: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Pages"
        href: pages/empty.qmd
        menu:
        - text: "Managers"
          href: pages/managers.qmd
        - text: "Anglers"
          href: pages/fishers.qmd
        - text: "Scientists"
          href: pages/scientists.qmd
        - text: "Data"
          href: pages/data.qmd
        - text: "Models"
          href: https://fishsizeproject.github.io/models/
        - text: "FishSize Project"
          href: pages/fishsizeproject.qmd
      - text: "Team"
        href: pages/team.qmd
      - text: "Media"
        href: pages/resources.qmd
      - text: "Contact"
        href: pages/contact.qmd
      - text: "{{< iconify flag lt-4x3 height=1em >}}"
        href: ../

format:
  html:
    theme: [lightly, theming/special-theming.scss]
    css: theming/sif-styles.css
    page-layout: full
    grid:
      sidebar-width: 350px
      body-width: 1250px
      margin-width: 150px
      gutter-width: 2em
    toc: false
    anchor-sections: false
    fig-responsive: true
    link-external-newwindow: true
    include-after-body:
      file: theming/footer-en.html
