# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  title: "Lydekai Paliepus | Sveikos ekosistemos kintančiame pasaulyje"
  output-dir: docs

lang: lt

website:
  title: "Lydekai Paliepus"
  description: "Sveikos ekosistemos kintančiame pasaulyje"
  favicon: images/SIF-LOGO-Lt.png
  # site-url: https://sif-quarto.drtreimer.com
  # repo-url: https://github.com/stormeyseas/sif-quarto.github.io
  page-navigation: false # Provide next and previous article links in footer
  back-to-top-navigation: true
  navbar: 
    background: light
    foreground: dark
    title: false
    logo: images/SIF-LOGO-Lt.png
    pinned: false
    collapse: true
    right: 
      - text: "Pradžia"
        href: index.qmd
      - text: "Puslapiai"
        menu:
        - text: "Programele"
          href: pages/managers.qmd
        - text: "Zvejams"
          href: pages/fishers.qmd
        - text: "Valdymui"
          href: pages/scientists.qmd
        - text: "Mokslui"
          href: pages/data.qmd
        - text: "Modeliai"
          href: https://fishsizeproject.github.io/models/
        - text: "Duomenys"
          href: pages/fishsizeproject.qmd
      - text: "Grupė"
        href: pages/team.qmd
      - text: "Media"
        href: pages/resources.qmd
      - text: "Susisiekite"
        href: pages/contact.qmd
      - text: "{{< iconify flag gb-4x3 height=1em >}}"
        href: en/

format:
  html:
    theme: [lightly, theming/special-theming.scss]
    css: theming/sif-styles.css
    page-layout: full
    grid:
      sidebar-width: 350px
      body-width: 1250px
      margin-width: 150px
      gutter-width: 2em
    toc: false
    anchor-sections: false
    fig-responsive: true
    link-external-newwindow: true
    include-after-body:
      file: theming/footer-lt.html
