# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  title: "Sustainable Inland Fisheries"
  output-dir: ./docs/en

lang: en

website:
  title: "Sustainable Inland Fisheries"
  description: "Healthy ecosystems in a changing world"
  favicon: images/SIF-logo-540x330.gif
  site-url: https://sif-quarto.drtreimer.com
  # repo-url: https://github.com/stormeyseas/sif-quarto.github.io
  # reader-mode: false
  # page-navigation: false
  # back-to-top-navigation: true
  navbar: 
    background: light
    foreground: dark
    title: false
    logo: images/SIF-logo-540x330.gif
    pinned: true
    collapse: true
    right:
      - text: "{{< iconify flag lt-4x3 height=1.25em >}}"
        href: javascript:ViewInLithuanian()
      - text: "Home"
        href: index.qmd
      - text: "Pages"
        href: pages/empty.qmd
        menu:
        - text: "Managers"
          href: pages/empty.qmd
        - text: "Anglers"
          href: pages/empty.qmd
        - text: "Scientists"
          href: pages/empty.qmd
        - text: "Data"
          href: pages/empty.qmd
        - text: "Models"
          href: pages/empty.qmd
        - text: "FishSize Project"
          href: pages/empty.qmd
      - text: "Team"
        href: pages/empty.qmd
      - text: "Media"
        href: pages/empty.qmd
      - text: "Contact"
        href: pages/empty.qmd
      - text: "{{< iconify flag gb-4x3 height=1.25em >}}"
        href: javascript:ViewInEnglish()

format:
  html:
    theme: [lightly, theming/special-theming.scss]
    css: theming/sif-styles.css
    page-layout: full
    grid:
      sidebar-width: 350px
      body-width: 1250px
      margin-width: 150px
      gutter-width: 2em
    toc: false
    anchor-sections: false
    fig-responsive: true
    link-external-newwindow: true
    include-after-body:
      file: theming/footer-lt.html
